version: '3.8'

services:

  postgres:
    image: postgres:17

    container_name: interviewforge-postgres

    environment:
      POSTGRES_DB: interviewforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: interviewforge-backend

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/interviewforge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      GEMINI_API_KEY: test-key

volumes:
  postgres_data: